version: '3.4'

services:
  cvbuilder.web:
    image: team2/cvbuilder.web
    build:
      context: .
      dockerfile: CVBuilder.web/Dockerfile
    env_file:
        - /Env/web.env
    volumes:
        - ./Logs/Web:/app/Logs/
    ports:
        - "8000:80"
    networks:
        customnetwork:
           ipv4_address: 172.20.0.10
  
  worker:
    image: team2/cvbuilder.worker
    build:
      context: .
      dockerfile: CVBuilder.Worker/Dockerfile
    env_file:
        - /Env/worker.env
    volumes:
        - ./Logs/worker:/app/Logs/
    
    networks:
        customnetwork:
           ipv4_address: 172.20.0.7
    depends_on:
        - cvbuilder.web

volumes:
    resume-data:
networks:
  customnetwork:
    ipam:
      config:
        - subnet: 172.20.0.0/16
